name: 'Docker Installation'
description: 'Install Docker Action for Linux'
outputs:
  random-number:
    description: "Docker version"
    value: ${{ steps.check-docker-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - run: bash <(curl -s https://raw.githubusercontent.com/docker/docker-install/master/install.sh)
      shell: bash
    - run: sudo usermod -aG docker ubuntu
      shell: bash
    - run: newgrp docker
      shell: bash
    - id: check-docker-version
      run: echo "version=$(docker version)" >> $GITHUB_OUTPUT
      shell: bash
